services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://heru:heru@cluster0.dgrghvi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      DB_NAME: emojipositiondb
      COLLECTION_NAME: positions
      PORT: 5000

